# Generated by Django 5.1.6 on 2025-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('iso_code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('capital', models.CharField(db_index=True, max_length=100, unique=True)),
                ('population', models.BigIntegerField(default=0)),
                ('area', models.FloatField(default=0, help_text='Km²')),
                ('continent', models.CharField(choices=[('Asia', 'Osiyo'), ('Europe', 'Yevropa'), ('Africa', 'Afrika'), ('North America', 'Shimoliy Amerika'), ('South America', 'Janubiy Amerika'), ('Oceania', 'Okeaniya'), ('Antarctica', 'Antarktika')], max_length=50)),
                ('currency', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('leader_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('leader_title', models.CharField(choices=[('President', 'Prezident'), ('Prime Minister', 'Bosh vazir'), ('King', 'Qirol')], max_length=50)),
                ('flag', models.ImageField(blank=True, default='img/default-image.png', null=True, upload_to='flags/')),
            ],
            options={
                'verbose_name': 'Davlat',
                'verbose_name_plural': 'Davlatlar',
            },
        ),
    ]
