# Generated by Django 5.1.6 on 2025-02-09 05:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.AddField(
            model_name='country',
            name='uuid',
            field=models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, editable=False, error_messages={'unique': 'This UUID already exists!'}, help_text='Auto-generated unique identifier for each country', primary_key=True, serialize=False, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
