# Generated by Django 5.1.6 on 2025-02-09 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_remove_country_id_country_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='uuid',
            field=models.UUIDField(db_column='uuid', db_index=True, default=uuid.UUID('f09a0518-d1fa-43d3-a704-19f4c2a29243'), editable=False, error_messages={'unique': 'This UUID already exists!'}, help_text='Auto-generated unique identifier for each country', primary_key=True, serialize=False, unique=True, verbose_name='Unique Identifier'),
        ),
    ]
