# Generated by Django 5.1.6 on 2025-02-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='uuid',
        ),
        migrations.AddField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
